name: chrysalis_mobile
description: "A Flutter-based mobile application for secure messaging and communication with real-time chat features, file sharing, and push notifications."
publish_to: 'none'

version: 1.1.0+10

environment:
  sdk: ^3.8.0

dependencies:
  basic_utils: ^5.7.0
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.3.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^17.2.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_web_plugins:
    sdk: flutter
  flutter_svg: ^2.2.0
  get_it: ^8.0.3
  logger: ^2.5.0
  open_file: ^3.5.10
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  pointycastle: ^3.7.4
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  sqflite: ^2.3.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2
  go_router: ^14.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  flutter_screenutil: ^5.9.3
  emoji_picker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_native_splash: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/localization/
    - .env

  fonts:
    # SF Pro Display Font Family
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SF-Pro-Display-Heavy.otf
          weight: 800

    # SF Pro Text Font Family
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SFProText/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProText/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProText/SF-Pro-Text-Heavy.otf
          weight: 800
